<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>DIEFER.Servicios</AssemblyName>
    <RootNamespace>DIEFER.Servicios</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DIEFER.BE\DIEFER.BE.csproj" />
  </ItemGroup>
</Project>
