<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>DIEFER.DAL</AssemblyName>
    <RootNamespace>DIEFER.DAL</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Data" />
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DIEFER.Servicios\DIEFER.Servicios.csproj" />
  </ItemGroup>
</Project>
